version: "3"

services:
  web:
    build: backend_main_django
    image: django_app
    volumes:
      - ./backend_main_django:/code
    environment: 
      SECRET_KEY: ${WEB_SECRET_KEY-REPLACE_ME}
      DEBUG: ${WEB_DEBUG-TRUE}
      DATABASE_URL: ${WEB_DATABASE_URL-postgres://test_k8s:OwOtBep9Frut@82.148.30.109:5432/test_k8s}
      ALLOWED_HOSTS: ${WEB_ALLOWED_HOSTS-127.0.0.1,localhost,alexmashukov.ru}
